---
- name: Verify cleaning parameters are defined and not empty
  ansible.builtin.assert:
    that:
      - stack_name is defined and stack_name|length
      - deployment_timestamp is defined and deployment_timestamp|length
    msg:
      - "stack_name must be defined an not empty"
      - "deployment_timestamp must be defined an not empty"

# remove old docker secrets
- name: "docker remove old stack secrets - {{ stack_name }} | listing"
  ansible.builtin.shell: >
    set -o pipefail &&
    docker secret ls | grep -zoP '.*\s+{{ stack_name|quote }}.*(\_|\-)(?!{{ deployment_timestamp|quote }})\d+.*\n'
    | awk '{print $2}' | sed -r '/^\s*$/d'
  register: docker_stack_secrets
  changed_when: false
  ignore_errors: true
  args:
    executable: /bin/bash

- name: "docker remove old stack secrets - {{ stack_name }} | removing"
  community.docker.docker_secret:
    name: "{{ item }}"
    state: absent
  with_items: "{{ docker_stack_secrets.stdout_lines }}"

# remove old docker configs
- name: "docker remove old stack configs - {{ stack_name }} | listing"
  ansible.builtin.shell: >
    set -o pipefail &&
    docker config ls | grep -zoP '.*\s+{{ stack_name|quote }}.*(\_|\-)(?!{{ deployment_timestamp|quote }})\d+.*\n'
    | awk '{print $2}' | sed -r '/^\s*$/d'
  register: docker_stack_configs
  ignore_errors: true
  changed_when: false
  args:
    executable: /bin/bash

- name: "docker remove old stack configs - {{ stack_name }} | removing"
  community.docker.docker_config:
    name: "{{ item }}"
    state: absent
  with_items: "{{ docker_stack_configs.stdout_lines }}"
...
